apiVersion: v1
kind: Secret
metadata:
  namespace: sam-ent-k8s-agents
  name: sam-procurement-workflow-secret
type: Opaque
stringData:
  NAMESPACE: "sam-ent-k8s"
  SOLACE_DEV_MODE: "false"
  SOLACE_BROKER_URL: "ws://host.docker.internal:8008"
  SOLACE_BROKER_USERNAME: "default"
  SOLACE_BROKER_PASSWORD: "default"
  SOLACE_BROKER_VPN: "sam"
  USE_TEMPORARY_QUEUES: "true"
  LLM_SERVICE_GENERAL_MODEL_NAME: "openai/claude-sonnet-4-6"
  LLM_SERVICE_ENDPOINT: "https://lite-llm.mymaas.net"
  LLM_SERVICE_API_KEY: "sk-cFW9MYGP60mUCvQI6TzMrQ"
  PERSISTENCE_TYPE: "sql"
  DATABASE_URL: "sqlite:///procurement_workflow.db"
  ARTIFACT_SERVICE_TYPE: "s3"
  S3_BUCKET_NAME: "sam-ent-k8s"
  S3_ENDPOINT_URL: "http://agent-mesh-seaweedfs-0.agent-mesh-seaweedfs.sam-ent-k8s.svc.cluster.local:8333"
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: "sam-ent-k8s"
  AWS_SECRET_ACCESS_KEY: "sam-ent-k8s"
